### ISSUE TITLE
Enable sharing logs

### ISSUE THREAD

**Issue by MamboBryan** [tabasumu/jambo#13]

**Comment by johnGachihi** [comment]
Can I help with this

**Comment by mawindavic** [comment]
Yea sure

**Comment by MamboBryan** [comment]
> Can I help with this

Go ahead, we would love to get more contributions

**Comment by johnGachihi** [comment]
I was thinking of adding the share button as a menu item on the bottom sheet's toolbar. What do you guys think about that?

**Comment by MamboBryan** [comment]
Since @mawindavic requested this feature I'll leave him to answer the details of the implementation.

**Comment by mawindavic** [comment]
@johnGachihi I think that will do. i presume this is the error sheet?

**Comment by johnGachihi** [comment]
Yes @mawindavic

**Comment by mawindavic** [comment]
> Yes @mawindavic

Yea. carry on
