### ISSUE TITLE
remove licence tag from readme.md

### ISSUE THREAD

**Issue by justtabasumu** [tabasumu/jambo#34]
There is a license tag added to the readme, we can remove it

**Comment by ArunKumar-07** [comment]
Hi @justtabasumu, I am newbie to open source .. can I remove the license tag??

**Comment by justtabasumu** [comment]
Hahaha @ArunKumar-07 we would love to have you contribute. Please do.
@MamboBryan please assits in any case

**Comment by ArunKumar-07** [comment]
> Hahaha @ArunKumar-07 we would love to have you contribute. Please do. @MamboBryan please assits in any case

Thanks  .. please review my PR .

**Comment by MamboBryan** [comment]
Thanks @ArunKumar-07 for the help
